// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Economic Crisis modding tools;

{ITE} {DFMFileType} {about.dfm}
{ITE} {DFMFileType} {CHILDWIN.dfm}
{ITE} {DFMFileType} {CountryEditor.dfm}
{ITE} {DFMFileType} {EquipmentEditor.dfm}
{ITE} {DFMFileType} {MAIN.dfm}
{ITE} {DFMFileType} {OptionsForm.dfm}
{ITE} {DFMFileType} {UnitEditor.dfm}
{ITE} {RCFileType} {Win32\Debug\Economic Crisis modding tools_DRC.rc}

{$R 'about.dfm' 'AboutBox:TForm'}
{$R 'CHILDWIN.dfm' 'MDIChild:TForm'}
{$R 'CountryEditor.dfm' 'CountryEditorForm:TForm'}
{$R 'EquipmentEditor.dfm' 'EquipmentEditorForm1:TForm'}
{$R 'MAIN.dfm' 'MainForm:TForm'}
{$R 'OptionsForm.dfm' 'SettingsForm:TForm'}
{$R 'UnitEditor.dfm' 'UnitEditorForm:TForm'}
{$R 'Win32\Debug\Economic Crisis modding tools_DRC.res' 'Win32\Debug\Economic Crisis modding tools_DRC.rc'}

{$E RUS}

begin
end.
